### ISSUE TITLE
Recent-ish issues getting plugin to function - ideas for debugging?

### ISSUE THREAD

**Issue by levouh** [Zakru/advanced-notifications#13]
I have used this plugin for a long time and have never had any issues. Recently, however, I have not been able to get the plugin to work at all.

Over time other plugins get installed, or their settings change, etc. which I imagine could conflict with this plugin indirectly. To try to debug this, I have gone through and created a fresh Runelite profile with _zero_ other plugins enabled and only advanced notifications, and cannot seem to get it to work regardless.

The example involves just a fresh Runelite profile being created and set as the default for the character in question, restarting Runelite, and setting up Advanced notifications for a very simple `+-` change to the inventory for an easy item (like `Pay-dirt` from Motherlode Mine).

Are there any steps you recommend beyond what is recommended above to debug this? The Runelite `client.log` also shows nothing of interesting (default log level seems to not show DEBUG level logs, which I would expect).

**Comment by Zakru** [comment]
Hey, thanks for the report!

As boilerplate, make sure the notification settings under the "RuneLite" config are what you expect. Mind you on a fresh profile, things like notifications while focused are disabled.

I can't repro the issue on my client with a fresh profile + `Pay-dirt +-` notification. I'd like to know are whether the Advanced Notifications panel shows up (indicating a complete failure in starting up).

For debugging, another point of interest is the config. There should be a format version and a JSON field describing the notification setup. Although if the plugin successfully restarts and reads it, it should be fine.

**Comment by levouh** [comment]
I always forget that Runelite has things like "do not notify if focused" by default. With a new profile and these settings fixed, it does work with just Advanced Notifications + Watchdog as the only 2 installed plugins.

The logs are littered with stack traces involving null pointer exceptions regarding the EventBus (which I assume is relatively critical path for handling events related to notification behavior). I am not sure if it is an issue with Runelite itself or a particular plugin (or both), but as the issue goes away when _just_ Advanced Notifications is installed, I cannot assume the issue is here.

I will go ahead and close this issue, thank you for the reply.
